### ISSUE TITLE
[Feat] 등록 물품 조회 (경매 반영)

### ISSUE THREAD

**Issue by Gyubam** [Senier-Project-Trade-Platform/backend#103]
## 📝  To-do
- [x] 작품 status 필드 추가
- [x] 관심작품 최소 가격 데이터 추가 반환
- [x] 등록 작품 조회 api 수정
