### ISSUE TITLE
[Feat] 작가 인증하기 기능 구현

### ISSUE THREAD

**Issue by ChooSeoyeon** [Senier-Project-Trade-Platform/backend#121]
## 📌  Description
- 사용자는 작가 인증 파일을 보낼 수 있다.
- 관리자는 작가 인증 파일을 보고 해당 사용자를 작가로 전환한다.

## 📝  To-do
- [x] 작가 인증 파일 올리는 api 구현
- [x] 작가 전환 api 관리자가 사용하게끔 리팩토링
- [x] 관리자 페이지에서 멤버 별 작가 인증 사진 띄우는 api

관리자 계정 생성은 일반 멤버로 회원 가입 후 직접 아래 sql문 날려서 roles를 관리자로 업데이트하기
`update member_roles set roles ='ROLE_ADMIN' where member_member_id=1;`
