### ISSUE TITLE
[Feat] 검색 기능 구현

### ISSUE THREAD

**Issue by Gyubam** [Senier-Project-Trade-Platform/backend#163]
## 📌  Description
- 사용자가 검색어를 통해 작품을 검색할 수 있습니다.
## 📝  To-do
- [ ] 최근 검색어 추가 api 
- [ ] 최근 검색어 조회 api
- [ ] 최근 검색어 단일 삭제 api
- [ ] 최근 검색어 전체 삭제 api
- [ ] 작품 검색 api
