### ISSUE TITLE
[Refactor] Member 리팩토링

### ISSUE THREAD

**Issue by ChooSeoyeon** [Senier-Project-Trade-Platform/backend#37]
## 🦾  Fix Description
- 프론트분들과 의논해 결정된 변경사항 반영

## 📝  To-do
- [x] 회원/작가 정보 수정API -> 빈문자열로도 수정되게 처리
    - 수정 안 한 필드는 null이 아닌 수정 전 값으로 받게 로직 수정은 나중에 처리 예정 (현재 수정 전 값 받을 수 있음)
- [x] 회원/작가 정보 수정API, 회원가입API -> 닉네임 중복확인 로직 추가
- [x] 닉네임 중복 검사 API 구현
- [x] 아이디 찾기API -> 닉네임 검증 로직 제거
- [x] email,id,닉네임 중복 검사 API -> response body 제거
- [x] 컨트롤러 반환값 통일되게 수정
- [x] 회원 정보 조회 API 통합 (get members/me)
