### ISSUE TITLE
[Feat] 채팅 기능 구현

### ISSUE THREAD

**Issue by JunYoung-C** [Senier-Project-Trade-Platform/backend#54]
## 📌  Description
작가와 회원 간의 채팅 기능 구현

## 📝  To-do
- [x] api 명세서 보완
- [x] 채팅 기능 구현
- [x] 테스트 코드 작성
