### ISSUE TITLE
[Feat] 채팅방 생성

### ISSUE THREAD

**Issue by JunYoung-C** [Senier-Project-Trade-Platform/backend#55]
## 📌  Description
기존에 채팅방이 존재하면 해당 채팅방의 id를 반환하고, 존재하지 않으면 신규 채팅방의 id를 반환한다.
채팅방이 없다면 새로운 채팅방을 생성하고, 있다면 다른 api로 리다이렉트 거는 방식으로 구현

## 📝  To-do
- [x] api 명세서 보완
- [x] 채팅방 생성 기능 구현
- [x] 테스트 코드 작성
