### ISSUE TITLE
[Feat] 채팅방 목록 조회 기능 구현

### ISSUE THREAD

**Issue by JunYoung-C** [Senier-Project-Trade-Platform/backend#56]
## 📌  Description
채팅방 목록과 각 채팅별 마지막 메세지 조회 기능 구현

## 📝  To-do
- [ ] api 명세서 보완
- [ ] 채팅방 목록 조회 기능 구현
- [ ] 테스트 코드 작성
