### ISSUE TITLE
[Feat] 채팅방 나가기 기능 구현

### ISSUE THREAD

**Issue by JunYoung-C** [Senier-Project-Trade-Platform/backend#57]
## 📌  Description
채팅방 나가기 요청 시 관련 채팅 제거 기능 구현

## 📝  To-do
- [x] api 명세서 보완
- [x] 채팅방 나가기 기능 구현
- [x] 테스트 코드 작성
